//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAPP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.242:1003/Live01/WS/Fiducia%20Limited%20-%20BAK/Page/newcontact")]
        public string ConsoleApplication1_NAVContactPageRef_newcontact_Service {
            get {
                return ((string)(this["ConsoleApplication1_NAVContactPageRef_newcontact_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.242:1003/Live01/WS/SystemService")]
        public string SFAPP_SystemServiceRef_SystemService {
            get {
                return ((string)(this["SFAPP_SystemServiceRef_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.242:1003/Live01/WS/Fiducia%20Limited%20-%20BAK/Page/CompanyInfo" +
            "rmation")]
        public string SFAPP_CompanyInfoRef_CompanyInformation_Service {
            get {
                return ((string)(this["SFAPP_CompanyInfoRef_CompanyInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.salesforce.com/services/Soap/c/37.0/0DF28000000PI7Z")]
        public string SFAPP_SFDC_SforceService {
            get {
                return ((string)(this["SFAPP_SFDC_SforceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.242:1003/Live01/WS/Fiducia%20Limited%20-%20BAK/Page/ContactRela" +
            "tion")]
        public string SFAPP_NAVContactRelPageRef_ContactRelation_Service {
            get {
                return ((string)(this["SFAPP_NAVContactRelPageRef_ContactRelation_Service"]));
            }
        }
    }
}
